### ISSUE TITLE
Subtitles doesn't work 

### ISSUE THREAD

**Issue by PabloAndresSB** [Stremio/stremio-bugs#584] opened 2023-10-21 21:46 UTC
Subtitles doesn't work on mi Nvidia Shield TV PRO (Android TV)

**Comment by TRtomasz** [comment] 2023-10-21 22:44
we are aware of this issue and we are working to fix it, thank you!

**Comment by Gp2mv3** [comment] 2023-10-22 10:12
Duplicate of #583

**Comment by TRtomasz** [comment] 2023-10-23 08:29
v3 addon has been released this should be now resolved

**Closed by TRtomasz** 2023-10-23 08:29 UTC
