### ISSUE TITLE
Cant use scrollwheel to scroll past 100% volume on the desktop version

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-bugs#495] opened 2023-08-26 09:10 UTC
**Describe the bug**
Before it was possible to scroll from 0 to 200% volume with the mouse scroll wheel.
Now it only scrolls till 100% and then stops.
After that you have to drag the indicator till 200% if you want to.

**To Reproduce**
Scroll to change the volume, and the indicator will get stuck at 100%

**Expected behavior**
Should scroll all the way till 200%

**Screenshots**
<img width="187" alt="stremio_64KA34UJql" src="https://github.com/Stremio/stremio-bugs/assets/47380919/4b6fc8a5-e662-4512-b894-5565a652694c">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version : Stremio 4.4.160, Web UI 4.4.163, Server 4.20.0

**Comment by Ivshti** [comment] 2023-08-26 17:43
@jaruba @tymmesyde is this intended behavior? Maybe the intention here is to avoid accidently putting the volume too high

**Comment by tymmesyde** [comment] 2023-08-27 13:55
Did not implement this feature but yes i guess this is intended, to prevent users from damaging their ears by miss scrolling

**Comment by TRtomasz** [comment] 2023-10-18 11:38
closing that one as this is intended behavior. Everything above the middle is artificial boost.

**Closed by TRtomasz** 2023-10-18 11:38 UTC
