### ISSUE TITLE
Trakt is not scrobbling on Nvidia shield TV (2015)

### ISSUE THREAD

**Issue by tundrablasen** [Stremio/stremio-bugs#479] opened 2023-07-23 07:36 UTC
I re-authenticated everything in my stremio user panel. logged out and logged in.
I deinstalled and re-installed the stremio app on my Nvidia Shield TV multiple times.
i cleared data and cache multiple times

**No Trakt Scrobbling is working.
Not after i finished watching an episode/movie (Stremio does not marked the media in trakt as "Watched").
Also the "Live Scrobbling" feature (that you see during playback on stremio, within the trakt website/App on the home screen what you are watching live right now including a progress bar) is not working**

Latest stremio app on all devices

**Trakt scrobble (even with Live scrobbeling) works fine on my amazon fire tv 4K max in bedroom.**

But same setup on Nvidia shield tv (2015), no live scrobbeling, and no scrobbeling at the end of the episode/movie.

Before 1.5.11 it was working as expected. Fine with normal scrobbling and live scrobbling. (i recall i had no issues when using 1.5.8. but cannot guarantee the software version)

Application: Stremio Android TV
Version: v1.5.11 (latest available version)
APK: from official play store
Device: Nvidia Shield TV (2015) - latest SW update installed.

**Comment by TRtomasz** [comment] 2023-07-24 08:06
@tundrablasen you might have to log out and log in again to stremio to refresh your user data so Stremio is aware of that trakt is logged in too.

**Comment by TRtomasz** [comment] 2023-07-24 10:22
I'm not able to reproduce the issue, scroblbing work fine, please remember it will not scrobble series that are unknown to the trakt or are played from an addon that does not provide a imdb id like most of the anime addons

**Comment by tundrablasen** [comment] 2023-08-02 19:36
It’s well known shows like narcos Mexico or the last of us.

and I use torrentio with Real Debrid. Scrobbeling always worked fine, before 1.5.8.

many idea that I can do now? I cleared data/cache multiple times. Deinstalled and installed the app. Logged out of Trakt in steemio account and re-authorised. 

Nothing works.

**Comment by TRtomasz** [comment] 2023-08-30 20:43
Closing it as we are not able to reproduce the issue and noone else is having such issue either.

**Closed by TRtomasz** 2023-08-30 20:43 UTC
