### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by seahindeniz** [Stremio/stremio-bugs#296] opened 2021-06-01 19:59 UTC
**Describe the bug**
After choosing a source from source list, I'm getting playback error even the source is download-able and valid(I think).
Even after receiving the playback error, Stremio keeps downloading the source media instead of terminating the connection.

**To Reproduce**
1. Search and go to `Lucifer`
2. Find season 5 and episode 12
3. Scroll down to first 720p
4. Play it

**Expected behavior**
Well, no errors at best.
A way to see some logs, outputs to identify the issue and to understand about what is going on and what's causing the error Whether it is something related to screen or codec or cache or something else, you know.
So that I can at least make some assumptions and try to find a solution.

**Screenshots**

https://user-images.githubusercontent.com/5789670/120382045-de913380-c32b-11eb-8aca-c27abf64f7f7.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

Desktop version of Stremio 4.4.137

**Comment by TRtomasz** [comment] 2021-06-02 10:26
I tried to play this file in VLC and it also fails to decode. Looks like the file is broken

**Comment by seahindeniz** [comment] 2021-06-02 16:01
Yeah, I kind of found the original file and download it. Seems like the problem is codec related 😐

MediaInfo result:
```
Video
ID                          : 1
Format                      : V_QUICKTIME
Codec ID                    : V_QUICKTIME
Duration                    : 58 min 44 s
Bit rate                    : 2 381 kb/s
Width                       : 1 280 pixels
Height                      : 720 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 24.000 FPS
Bits/(Pixel*Frame)          : 0.108
Stream size                 : 1 000 MiB (77%)
Language                    : English
Default                     : Yes
Forced                      : No
```
<details>
<summary>All of it</summary>

```
General
Unique ID                   : 15210261791072084490347885737517689883 (0xB7163CE2996EB2FBFC618050112AC1B)
Complete name               : C:\Users\Sahin\Downloads\Lucifer.S05E12.720p.WEB.h264-GOSSIP[eztv.re].mkv
Format                      : Matroska
Format version              : Version 4
File size                   : 1.26 GiB
Duration                    : 58 min 44 s
Overall bit rate            : 3 082 kb/s
Writing application         : mkvmerge v57.0.0 ('Till The End') 64-bit
Writing library             : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                          : 1
Format                      : V_QUICKTIME
Codec ID                    : V_QUICKTIME
Duration                    : 58 min 44 s
Bit rate                    : 2 381 kb/s
Width                       : 1 280 pixels
Height                      : 720 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 24.000 FPS
Bits/(Pixel*Frame)          : 0.108
Stream size                 : 1 000 MiB (77%)
Language                    : English
Default                     : Yes
Forced                      : No

Audio
ID                          : 2
Format                      : E-AC-3
Format/Info                 : Enhanced AC-3
Commercial name             : Dolby Digital Plus
Codec ID                    : A_EAC3
Duration                    : 58 min 44 s
Bit rate mode               : Constant
Bit rate                    : 640 kb/s
Channel(s)                  : 6 channels
Channel layout              : L R C LFE Ls Rs
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Compression mode            : Lossy
Stream size                 : 269 MiB (21%)
Language                    : English
Service kind                : Complete Main
Default                     : Yes
Forced                      : No

Text #1
ID                          : 3
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Arabic
Language                    : Arabic
Default                     : No
Forced                      : No

Text #2
ID                          : 4
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Czech
Language                    : Czech
Default                     : No
Forced                      : No

Text #3
ID                          : 5
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Danish
Language                    : Danish
Default                     : No
Forced                      : No

Text #4
ID                          : 6
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Greek
Language                    : Greek
Default                     : No
Forced                      : No

Text #5
ID                          : 7
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : English (SDH)
Language                    : English
Default                     : No
Forced                      : No

Text #6
ID                          : 8
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Spanish
Language                    : Spanish
Default                     : No
Forced                      : No

Text #7
ID                          : 9
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : European Spanish
Language                    : Spanish
Default                     : No
Forced                      : No

Text #8
ID                          : 10
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Finnish
Language                    : Finnish
Default                     : No
Forced                      : No

Text #9
ID                          : 11
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : French
Language                    : French
Default                     : No
Forced                      : No

Text #10
ID                          : 12
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Hebrew
Language                    : Hebrew
Default                     : No
Forced                      : No

Text #11
ID                          : 13
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Hungarian
Language                    : Hungarian
Default                     : No
Forced                      : No

Text #12
ID                          : 14
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Indonesian
Language                    : Indonesian
Default                     : No
Forced                      : No

Text #13
ID                          : 15
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Italian
Language                    : Italian
Default                     : No
Forced                      : No

Text #14
ID                          : 16
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Japanese
Language                    : Japanese
Default                     : No
Forced                      : No

Text #15
ID                          : 17
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Korean
Language                    : Korean
Default                     : No
Forced                      : No

Text #16
ID                          : 18
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Norwegian
Language                    : Norwegian
Default                     : No
Forced                      : No

Text #17
ID                          : 19
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Dutch
Language                    : Dutch
Default                     : No
Forced                      : No

Text #18
ID                          : 20
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Polish
Language                    : Polish
Default                     : No
Forced                      : No

Text #19
ID                          : 21
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Portuguese
Language                    : Portuguese
Default                     : No
Forced                      : No

Text #20
ID                          : 22
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Brazilian Portuguese
Language                    : Portuguese
Default                     : No
Forced                      : No

Text #21
ID                          : 23
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Romanian
Language                    : Romanian
Default                     : No
Forced                      : No

Text #22
ID                          : 24
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Russian
Language                    : Russian
Default                     : No
Forced                      : No

Text #23
ID                          : 25
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Swedish
Language                    : Swedish
Default                     : No
Forced                      : No

Text #24
ID                          : 26
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Thai
Language                    : Thai
Default                     : No
Forced                      : No

Text #25
ID                          : 27
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Turkish
Language                    : Turkish
Default                     : No
Forced                      : No

Text #26
ID                          : 28
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Vietnamese
Language                    : Vietnamese
Default                     : No
Forced                      : No

Text #27
ID                          : 29
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Simplified Chinese
Language                    : Chinese
Default                     : No
Forced                      : No

Text #28
ID                          : 30
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Traditional Chinese
Language                    : Chinese
Default                     : No
Forced                      : No

```
</details>

Torrent hash [861BE4D34A5E43FAEB47E259B8DE406926834DD9](https://bit.ly/2RgAyuX)

Well, now at least I have an explanation about what's happening

**Comment by seahindeniz** [comment] 2021-06-02 16:06
I wish there was some sort of moderation system where we can vote sources such as this file to be reviewed and moderated by some volunteer community members who can identify this kind of problems and mark the sources as invalid for not to be listed in the first place.

It's like [SponsorBlock](https://sponsor.ajay.app/), and it's vote/report based moderation system

**Comment by jaruba** [comment] 2021-06-04 14:29
Given that this is not a bug in the app, I am closing it.

@seahindeniz if you wish to make a feature request, please do so at https://github.com/Stremio/stremio-features and also ensure that the same feature request doesn't already exist

**Closed by jaruba** 2021-06-04 14:29 UTC
