### ISSUE TITLE
Stremio Chromecast Subtitles are BIG (can't be changed)

### ISSUE THREAD

**Issue by iiiii12** [Stremio/stremio-bugs#291] opened 2021-05-13 20:01 UTC
Stremio Chromecast Subtitles size is BIG and it can't be changed at all. Tried to change the size and never succeeded. it's ok while watching through the phone but when broadcast it to ANY TV through Chromecast it gets too big!!

 - Android 11 - OnePlus
 - Stremio Version 1.3.6

**Comment by iiiii12** [comment] 2021-06-05 16:29
Anyone to support?

**Comment by TRtomasz** [comment] 2021-06-07 06:41
Sorry, i',m not able to reproduce this issue. Please tell us exatly which video and stream you have tried when this happend.

**Comment by iiiii12** [comment] 2021-06-07 14:56
Any movies played in Strmio in my mobile. When I broadcast them through Chromecast and activate the Subtitles, I get these subtitles in a very huge size that I cannot reduce.

By the way, I've seen this issue happening to so many people in the internet when I searched about it. So many people are suffering from the same issue with no end to this issue.

**Comment by TRtomasz** [comment] 2021-06-07 21:46
@iiiii12 please tell us which exact stream you have tried otherwise i will not be able to reproduce this issue. Also please tell me which subtitles you have used

**Comment by iiiii12** [comment] 2021-06-08 14:05
I mentioned that already "any movies". If you are referring to something else, please tell me an example so that I get your point.

As for the subtitles, all subtitles of any languages are having the same problem (big size).

**Comment by TRtomasz** [comment] 2021-06-08 15:32
@iiiii12  Please make a screenshot and mark on it stream you picked and caused you issues
 below you can see what i mean
![image](https://user-images.githubusercontent.com/40594253/121214554-21489380-c877-11eb-974a-3e043cc29ad7.png)

**Comment by iiiii12** [comment] 2021-06-08 18:28
Clear to me now. First picture shows the stream.

![Screenshot_20210608-212056](https://user-images.githubusercontent.com/84153534/121237980-4bfb1200-c8a0-11eb-9f96-220485851863.jpg)



Second picture shows the subtitle size that I chose which is (8). Even if I reduce it to 2 or even to 1, it does not get reduced in the TV.

![Screenshot_20210608-211949](https://user-images.githubusercontent.com/84153534/121238023-56b5a700-c8a0-11eb-9996-b4124b04d6a5.jpg)



Third picture is the movie in the TV and you can see how big the subtitle is (which I cannot make it smaller at all).

![IMG_20210608_212038](https://user-images.githubusercontent.com/84153534/121238085-62a16900-c8a0-11eb-8095-87b926a2e9de.jpg)

**Comment by iiiii12** [comment] 2021-06-12 08:49
@TRtomasz waiting for your support :)

**Comment by carlosvsilva** [comment] 2021-06-12 20:08
Also happens in my Stremio in Android phone streaming to Android TV via Chromecast. When I watch anything like Birds of Prey: The emancipation of Harley Quinn or The Good Doctor (highest quality) the subtitles take like 1/3 of the screen. Sizing them on the phone has no effect on the screen.
Also when I run Stremio 32bit natively in Philips Android TV the video stutters and audio is out of sync, please fix it. Thanks a lot your software is amazing.

**Comment by iiiii12** [comment] 2021-06-23 14:49
I've seen this issue happening to many people in this forum as well as others but no one cared to fix it...

**Comment by iiiii12** [comment] 2021-07-02 04:39
Anyone to help?

**Comment by TRtomasz** [comment] 2021-07-02 08:15
We are working on new version that will have this issue fixed.

**Comment by iiiii12** [comment] 2021-07-03 05:43
Excellent news. Thank you so much for this news and for having this great app 👍👍👍

**Comment by TRtomasz** [comment] 2021-08-09 08:47
Hi, New version has been released a while ago and this issue should be fixed now.

**Closed by TRtomasz** 2021-08-09 08:47 UTC
