### ISSUE TITLE
Some series like "Breaking Bad" throws: "Error fetching item data"

### ISSUE THREAD

**Issue by tomay3000** [Stremio/stremio-bugs#195] opened 2019-10-15 17:46 UTC
<a href="https://imgur.com/HbJW0M2.png">
  <img src="https://imgur.com/HbJW0M2.png" />
</a>

As illustrated in the screenshot:
It was working before until I become seeing this error, I need to know what is the location of the installed addons so I can remove them manually and reset Stremio.

I am running **stremio-4.4.77-2** under **Manjaro Linux Xfce 4.14.1 x86_64**
What could be the problem anyway!?

**Comment by Ivshti** [comment] 2019-10-16 08:28
The addon providing info for this is Cinemeta, which should be impossible to remove. We'll have someone look into this.

**Comment by TRtomasz** [comment] 2019-10-16 09:15
Hi @tomay3000  can you go to the addons settings (puzzle icon) Official add-ons section and check if Cinemeta addon is installed?

**Comment by tomay3000** [comment] 2019-10-16 11:32
@TRtomasz Cinemeta addon is installed, but I want to reinstall it, but stremio won't let me do so.
I also have Popcorn Time installed.
About Pimp my stremio or Stremio downloader apps, I haven't installed'em.

**Comment by TRtomasz** [comment] 2020-01-15 09:08
Couldn't reproduce this, since no one else reported such error i'm closing it for now

**Closed by TRtomasz** 2020-01-15 09:08 UTC

**Comment by PabloRai** [comment] 2020-10-12 22:33
@TRtomasz Hi, how are you?

I have the same issue 

![imagen](https://user-images.githubusercontent.com/26840336/95795797-a61be700-0cc1-11eb-8294-277cd333db1e.png)

Can you please take a look ? How can I provide you with more information? (I have the last version of stremio, and it happens in windows and android)

**Comment by TRtomasz** [comment] 2020-10-13 07:30
@PabloRai simply tell us for what movie/series does it happen.
Also please try using another account to check if it happens then.

**Comment by PabloRai** [comment] 2020-10-13 15:34
Hello @TRtomasz for me the serie was 'The haunting of bly manor', but I tried a few more series in cinemata (randomly) and I got the same issue.

**Comment by radmax37** [comment] 2020-10-24 22:25
I’m also having this issue for bly manor when I try to watch among other shows, do I have to delete and reinstall ?

**Comment by radmax37** [comment] 2020-10-24 22:26
> I’m also having this issue for bly manor when I try to watch among other shows, do I have to delete and reinstall ?

I also have cinemeta installed and tried with both guest and logged in account

**Comment by PabloRai** [comment] 2020-11-06 02:06
Hello @TRtomasz can you please take a look to this issue? Is ther something I can do to help you?

**Comment by omvsj** [comment] 2021-01-28 14:43
I'm also having this issue for 1986 The Act (2020) movie. https://www.imdb.com/title/tt12708236/?ref_=fn_al_tt_1

**Comment by seahindeniz** [comment] 2021-02-17 05:55
Same here with Hortensia Saga!

![1ec15cb2-9607-4fb5-a3f5-89dfc5861555](https://user-images.githubusercontent.com/5789670/108162210-b0ca0b00-70fd-11eb-8b13-4cab6e7f2c50.gif)

**Comment by Ivshti** [comment] 2021-02-19 16:58
@seahindeniz you should try the following:
1. open https://app.strem.io/shell-v4.4 and see if the problem exists there
2. try disabling your firewall or antivirus
3. try disabling ipv6

**Comment by seahindeniz** [comment] 2021-02-19 17:51
Yeah, the same problem exists there as well. I've gone deep a bit and found a problem already! <sub>_Thanks to that link_</sub>

This is the link to a JSON output of the Breaking bad series and output is just looks fine
https://v3-cinemeta.strem.io/meta/series/tt0903747.json
![image](https://user-images.githubusercontent.com/5789670/108541637-bdb04f80-72f3-11eb-8a47-f9dbb1a8e0c3.png)

And this is the link for the Hortensia Saga series and output is not good
https://v3-cinemeta.strem.io/meta/series/tt13266422.json
![image](https://user-images.githubusercontent.com/5789670/108541765-e5071c80-72f3-11eb-8154-3a6a33e477b3.png)

**Comment by seahindeniz** [comment] 2021-03-17 06:42
Kind of similar thing happens on "The Irregulars" series entry as well. 
![image](https://user-images.githubusercontent.com/5789670/111425621-7e173080-8704-11eb-8e11-bedba102c525.png)

APIs are also returning with false responses
https://5db836ec3ef8-thepiratebay-ctl.baby-beamup.club/meta/series/tt10893694.json `🔴 500`
https://v3-cinemeta.strem.io/meta/series/tt10893694.json `empty object {}`

**Comment by seahindeniz** [comment] 2021-03-17 06:43
Hey @TRtomasz, I think this issue needs to be reopened

**Comment by Juanmalopezg** [comment] 2021-07-11 23:17
Hi @TRtomasz! Same problem here with "The Wire".
![stermio_bug](https://user-images.githubusercontent.com/31255822/125212515-51bf8b00-e284-11eb-92cf-5881410e5724.gif)

I am running the 4.4.1142 version under Windows 10 Home 10.0.19042
