### ISSUE TITLE
Error while applying shell JS

### ISSUE THREAD

**Issue by sispus** [Stremio/stremio-bugs#174] opened 2019-01-14 00:13 UTC
Hi,
I just installed stremio 4.4.25 on manjaro linux using .xz file downloaded from the stremio.com
(I was using appimage before that). It gives the error whenever I started the app:
```
 "Error while applying shell JS. Please consider re-installing Stremio from https://www.stremio.com"
"no viable transport found (qt.webChannelTransport)"
```
I'm just clicking the "ok" button and it is gone. The app works without problem, I guess.

Is it a problem that I need to bother?

Thank you for super app, by the way.

**Comment by KrissHackerCat** [comment] 2019-02-17 12:47
I have the same problem on Manjaro Linux 18.0.2

**Comment by sispus** [comment] 2019-02-17 17:47
for manjaro: aur package stremio-beta is updated and 4.4.25.1 works without this problem.
https://aur.archlinux.org/packages/stremio-beta

**Comment by glaubersm** [comment] 2019-02-19 13:25
Same bug here. I use Arch Linux, I installed stremio using the package from stremio website.

**Comment by techmedixx** [comment] 2019-02-21 08:52
I am experiencing the same thing on KDE Neon 18.04 user edition. I also had the appimage problem as 'sispus' and then switched to 4.4.25.1 deb installation.

**Comment by KrissHackerCat** [comment] 2019-02-22 11:02
> for manjaro: aur package stremio-beta is updated and 4.4.25.1 works without this problem.
> https://aur.archlinux.org/packages/stremio-beta

thank's
i'll try

**Comment by qbss** [comment] 2019-04-12 20:57
I'm having this same issue with latest version as of today (Web UI 4.453) on Abuntu 1904 after applying updates.  I'm running the same version on another box running Abuntu 18.04 LTS and it still works fine with the latest updates applied.  

I've also noticed that it will initially work after a fresh boot/restart (after clicking OK to the same error message), but when attempting to play something a 2nd time I just get a blank screen after selecting a source.  Unless I come across a resolution or another update corrects the problem, I will probably reload this box with Ubuntu 18.04 LTS to get it working again.

**Comment by jscmal** [comment] 2019-04-20 14:52
Hi, after a clean Installation of Ubuntu 19.04, now I experience the same bug. Besides, the software doesn't make the Login, using the Facebook Login Button (maybe also using the email and password).

is there any fixing?

**Comment by qbss** [comment] 2019-04-20 20:02
I resolved the problem by installing Ubuntu 18.04.2 LTS since I didn’t come across any fixes and running the LTS version would most likely be more stable.  Although it currently works fine under 18.04.. I’ll certainly be cautious when loading updates!


________________________________

**Comment by jsf15** [comment] 2019-04-21 11:38
same problem as @jscmal

**Comment by fobos531** [comment] 2019-04-22 09:47
Same issue here

**Comment by manolli** [comment] 2019-04-23 16:06
same issue here, ubuntu 19.04 - .deb instalation

**Comment by TRtomasz** [comment] 2019-04-23 21:19
@manolli please check this version https://dl.strem.io/linux/v4.4.54/stremio_4.4.52-1_amd64.deb

**Comment by fobos531** [comment] 2019-04-24 12:31
> @manolli please check this version https://dl.strem.io/linux/v4.4.54/stremio_4.4.52-1_amd64.deb

I can confirm that this release fixed multiple issues. For me it fixed:
- "Error while applying shell JS" issue
- Login with Facebook
- Icon not displayed properly (blacked out) in GNOME application list (this has been an issue for me before and it's fixed now)

Thank you for this release, to you and everyone involved.

**Comment by manolli** [comment] 2019-04-24 12:40
@fobos531 thank you,
the application is working well now.

**Closed** 2019-04-25 10:28 UTC
