### ISSUE TITLE
Skip end credits button disappeared 

### ISSUE THREAD

**Issue by SSwaggerSoulss** [Stremio/stremio-bugs#477] opened 2023-07-18 21:57 UTC
A few updates ago the green button in the bottom right corner to skip end credits disappeared on Android TV.

I tried adjusting the seconds for when the button should appear but no luck.

Device: Android TV
OS version: Android 9
Stremio version: 1.5.11

**Comment by SSwaggerSoulss** [comment] 2023-07-19 16:02
Next video pop up duration is set to 35s and auto play next episode is enabled.

**Comment by jaruba** [comment] 2023-07-19 16:07
maybe the reason you don't see it is because you press the next video button manually in the UI prior to reaching 35s before the video ends?

**Comment by SSwaggerSoulss** [comment] 2023-07-19 16:09
I tried manually skipping to the last seconds of the episode and still don't see it unfortunately.

**Comment by TRtomasz** [comment] 2023-07-20 08:31
yeah @SSwaggerSoulss  please do it if possible i guess it can be usefull.

**Comment by SSwaggerSoulss** [comment] 2023-07-20 19:15
Sorry for my late reply.

Uploaded the video to my mega cloud.

Please find the link below:

https://mega.nz/file/NZUnxCZa#ycrWYXM_xIBzV70GVPb6peX4ByKIbaZMcbqtuPdeY-U

**Comment by SSwaggerSoulss** [comment] 2023-07-20 19:20
So far I have tried with no success:

1. Switching off tunneled playback
2. Switching off auto play next video
3. Switching to libVLC player
4. Reinstalling Stremio

**Comment by TRtomasz** [comment] 2023-07-21 09:23
thanks, will check this out, maybe it only happens when you play something from continue watching

**Comment by SSwaggerSoulss** [comment] 2023-07-21 15:37
Thanks for checking! Just tried a random tv series I have not watched before and skipped to the last few seconds and unfortunately still don't see the button. Do you think an addon might be causing this? I can list all the addon I have installed.

**Comment by SSwaggerSoulss** [comment] 2023-07-21 15:49
Actually I just tried with a brand new account with only one add-on installed and I still don't see the bottom so I guess I don't shouldn't be an issue.

**Comment by TRtomasz** [comment] 2023-07-21 15:56
Hi, thanks for the update i will try next week again to see if i can reproduce this issue

**Comment by SSwaggerSoulss** [comment] 2023-07-24 13:40
Hi, I am using torrentio. Worked fine with the version where you first introduced the feature but at some point it stopped working. Maybe I can test it, do you have by any chance the old version?

**Comment by TRtomasz** [comment] 2023-08-30 20:44
Closing as we can't reproduce this issue.

**Closed by TRtomasz** 2023-08-30 20:44 UTC
