### ISSUE TITLE
Stremio broken after upgrade to 3.5.9 - ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by lovromazgon** [Stremio/stremio-bugs#46] opened 2016-03-25 16:12 UTC
Last time I was using 3.5.7 everything worked correctly, but after upgrading to 3.5.9 Stremio doesn't work. First it showed me the message `Warning: no Stremio add-on active for this type. Showing saved items, nothing here will update.` so I reinstalled Stremio from scratch and removed the folder `.config/stremio`. Then I couldn't even sign up or log in, the error on the screen said "Failed to fetch"

After running stremio with `--development` I think I found the problem - it looks like there's a problem with the connection, particularly with the SSL protocol.

Console output:

> Error: ENOENT: no such file or directory, open '/home/lovro/.config/stremio/.linvo-user'(…)
> Remote: disabled
> pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.
> /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
> GET https://www.google-analytics.com/analytics.js net::ERR_SSL_PROTOCOL_ERROR
> GET https://channels.strem.io/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsXSwibWV0aG9kIjoibWV0YSIsImlkIjoxLCJqc29ucnBjIjoiMi4wIn0= net::ERR_SSL_PROTOCOL_ERROR
> TypeError: Failed to fetch(…) "https://channels.strem.io/stremioget"
> GET https://filmon.strem.io/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsXSwibWV0aG9kIjoibWV0YSIsImlkIjoxLCJqc29ucnBjIjoiMi4wIn0= net::ERR_SSL_PROTOCOL_ERROR
> TypeError: Failed to fetch(…) "https://filmon.strem.io/stremioget"
> GET https://cinemeta.strem.io/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsXSwibWV0aG9kIjoibWV0YSIsImlkIjoxLCJqc29ucnBjIjoiMi4wIn0= net::ERR_SSL_PROTOCOL_ERROR
> TypeError: Failed to fetch(…) "https://cinemeta.strem.io/stremioget"
> GET https://guidebox.strem.io/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsXSwibWV0aG9kIjoibWV0YSIsImlkIjoxLCJqc29ucnBjIjoiMi4wIn0= net::ERR_SSL_PROTOCOL_ERROR
> TypeError: Failed to fetch(…) "https://guidebox.strem.io/stremioget"
> GET https://api9.strem.io/addons5 net::ERR_SSL_PROTOCOL_ERROR
> Reducing cache size to 2048MB from 0MB by deleting 0 files
> GET https://api9.strem.io/addons5 net::ERR_SSL_PROTOCOL_ERROR

**Comment by Ivshti** [comment] 2016-03-25 16:27
Yep, we changed it to use https for everything. It seems that's causing issues on some Linux installations, now the question is to verify on which and why.

**Comment by lovromazgon** [comment] 2016-03-25 16:33
Well, I'm using Ubuntu 15.10. If you need more information I'm happy to help. Meanwhile - is there a way to change the URLs back to http manually?

**Comment by Ivshti** [comment] 2016-03-25 16:34
@lovromazgon no, but if we don't figure out how to fix this I'll add a flag --no-https

**Comment by Ivshti** [comment] 2016-03-25 16:34
otherwise you can get http://www.strem.io/Stremio3.5.7.linux.tar.gz

**Comment by VosaXalo** [comment] 2016-03-25 18:05
This is exactly the same situation I have on my system.
Ubuntu 14.04 LTS 64bit. No plugins, no login, no more search function.

**Comment by VosaXalo** [comment] 2016-03-25 18:12
@Ivshti It exists an option to stay with the version 3.5.7? I ask because every time I run this version, the client update itself automatically to version 3.5.9, and the issue is there again.

**Comment by CorneliusDranto** [comment] 2016-03-27 23:02
Same issue with OSX 10.11.4
login works
search and loading does not work

**Comment by jonjonhg** [comment] 2016-04-03 07:37
Same issue withbut with windows 10

**Comment by lovromazgon** [comment] 2016-04-07 14:59
@Ivshti Anything new about this bug / fix?

**Comment by Ivshti** [comment] 2016-04-09 17:20
Read this:
https://productforums.google.com/forum/#!topic/chrome/gWOCNmiVtfQ

**Comment by G-Ray** [comment] 2016-04-11 19:07
Also see https://github.com/popcorn-official/popcorn-desktop/issues/9

**Comment by Ivshti** [comment] 2016-04-11 19:09
@G-Ray yep, IMO it can happen on any app that uses https as long as there's something blocking it

**Comment by esoteric1** [comment] 2016-05-08 01:40
Same for me. Macbook pro.  OS X 10.11.3

**Comment by Ivshti** [comment] 2016-05-08 09:20
@esoteric1 @lovromazgon @jonjonhg @CorneliusDranto @VosaXalo 

We thought this was fixed in 3.5.11/.12 because we implemented fallback to HTTP. For some reason, it  hasn't solved the issue completely

Can you all try this version -> http://www.strem.io/Stremio3.5.13.exe
http://www.strem.io/Stremio3.5.13.dmg
http://www.strem.io/Stremio3.5.13.linux.tar.gz

And let us know how it works

**Comment by VosaXalo** [comment] 2016-05-08 14:14
Tried v. 3.5.13 on Ubuntu Linux 14.04 and so far so good :-)
All seems to work correctly.

**Comment by esoteric1** [comment] 2016-05-08 19:23
I tried it (3.5.13).  but after I installed it, i got a pop up saying it
"upgraded" to 3.5.12 and it would be in effect one I restarted it it said
it was on 3.5.12 and everything still worked

**Closed** 2016-05-18 09:45 UTC

**Comment by Harith163** [comment] 2016-09-01 03:12
I am having this same issue on 3.6.5 for win 10. If I use the regular installer, it keeps telling me to connect to a network(even though i am). If I press ok, the progress bar moves a bit and then it pops up again. Help please

**Comment by Ivshti** [comment] 2016-09-01 09:48
@Harith163 try this: http://dl.strem.io/Stremio%203.6.5.exe

**Comment by Harith163** [comment] 2016-09-02 02:01
@Ivshti I tried it.... Still no luck. I am still unable to login

**Comment by Ivshti** [comment] 2016-09-02 12:57
@Harith163 did you try another connection?

**Comment by Harith163** [comment] 2016-09-02 12:59
Yes I did. Unfortunately, the new connection is a university wide
connection. From my understanding, cloudflare doesn't quite like that
either. I won't be able to connect to any other networks until Christmas
I'm afraid

On 02-Sep-2016 8:57 am, "Ivo Georgiev" <notifications@github.com> wrote:

@Harith163 <https://github.com/Harith163> did you try another connection?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Stremio/stremio-bugs/issues/46#issuecomment-244367378>,
or mute the thread

**Comment by Ivshti** [comment] 2016-09-02 13:37
@Harith163 just to confirm, web version works (alpha4.strem.io) ?

any chance to arrange a teamviewer access so i can try to fix it from your end?

**Comment by Harith163** [comment] 2016-09-02 14:06
The web viewer works. I don't however, want to set up team viewer. Even
though I trust you, my own paranoia wouldn't let me. Sorry. More over, uni
just started for me, I wouldn't be free. Thanks for the offer though.

Could you possibly just tell me which files are doing the damage?

**Comment by Ivshti** [comment] 2016-09-02 14:26
@Harith163 it's not about files, it's about the fact cloudflare decides to block some users. It's not avoidable at the moment, unless changing the user agent of Electron fixes it.

another option is for me to try to add an exception in cloudflare somehow; i'm gonna need at least an ip for that though

**Comment by coreboy84** [comment] 2016-09-06 21:23
Similar issue here. Can't loguin or sign as guest after upgrading from 3.6.2 to the latest version 3.6.5... I've tested two different connections (two ISP) with no luck. Attached is the --development output. I'm on linux debian 64 bits. 

Thanks.

![image](https://cloud.githubusercontent.com/assets/22038124/18291200/034571aa-745d-11e6-9c6d-454f74e9619e.png)

**Comment by Ivshti** [comment] 2016-09-09 13:29
@coreboy84 the same question applies to you - does the web version work - http://alpha4.strem.io 
note that everything but filmon (Discover->Channels) is disabled to stream in the web version

**Comment by coreboy84** [comment] 2016-09-09 15:31
Doesn't work. I only see just a blank page when accessing to http://alpha4.strem.io   ...
I've tried three browsers and three different ISPs.
