### ISSUE TITLE
Volume increases only halfway when using the scroll wheel

### ISSUE THREAD

**Issue by KleoPetroff** [Stremio/stremio-bugs#499] opened 2023-08-26 16:49 UTC
**Describe the bug**
The volume increases only to 50% when using the scroll wheel. Also, when the volume is at maximum and you lower it using the scroll wheel, the volume is directly set to 50%.

**To Reproduce**
1. Start any movie or TV show
2. Increase or decrease the volume
2.1 Using the keyboard arrows or clicking on the volume bar to increase the volume to > 50%
2.2 Scroll down (decrease the volume)

**Expected behavior**
The volume should go above 50% and if the volume is set to above 50% it should properly decrease or increase in steps

**Screenshots**
![Stremio_volume_bug](https://github.com/Stremio/stremio-bugs/assets/8289691/685b8ce1-90d6-40a7-8092-f76d72a8fa1b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: - 
 - Version:  4.4.160

**Additional context**
Using the keyboard arrows or selecting the volume using mouse clicks seems to work fine.

**Comment by Ivshti** [comment] 2023-08-26 17:43
seems like a dupe of #495 but this could be intended behavior

**Closed by Ivshti** 2023-08-26 17:43 UTC

**Comment by dexter21767-dev** [comment] 2023-08-26 17:50
what you're referring to as 50% is actually 100% volume, the non-purple part is +100% (boosted) like in vlc where you can put volume to 200% but that will come in exchange of audio quality.

**Comment by KleoPetroff** [comment] 2023-08-26 18:59
> what you're referring to as 50% is actually 100% volume, the non-purple part is +100% (boosted) like in vlc where you can put volume to 200% but that will come in exchange of audio quality.

Without any text indication, it's difficult to know where the 100% is, but you make a good point. The yellow and red parts seem to be introduced with the new UI.

This doesn't change the fact that the current behavior is not consistent though - you can only go to the middle of the bar using the scroll wheel, yet using the arrow keys or mouse clicking you can easily increase the volume further. The jump to the middle of the bar when lowering the volume using the wheel just adds to the confusion. 

In my opinion, if the boosted volume is indeed intentional, you should still be able to scroll through it consistently and without any restrictions. VLC does it that way, they even show the percentage below their volume bar, which to me is the best user experience for this kind of feature.

**Comment by dexter21767-dev** [comment] 2023-08-26 21:46
@KleoPetroff i agree that it should be communicated better to the user for a better user experience. but with the new redesign, the top priority should be for system-breaking bugs, and then everything comes after. but hopeful an improvement regarding this matter will be discussed.
