### ISSUE TITLE
Webos unable to change audio track 

### ISSUE THREAD

**Issue by Doffy111** [Stremio/stremio-bugs#788] opened 2024-05-13 06:42 UTC
**Describe the bug**
Unable to change audio track on. Web os stemio client
I can change audio track on pc and mobile its not available on lg web os
I tried putting default track to english
Setting english on pc
First and second language to english on web os
Nothing seems to work it just wont play in english it always chooses any other random audio stream in them movie but wont play in english

**Expected behavior**
It would let me change audio tracks available with video which is easily possible on phone and pc

**Screenshots**

**TV (please complete the following information):**
 - Device: lg c2 42
 - OS: web os
 - Version webos23

**Additional context**
The app is great thanks for your work please update and squash those bugs soon

**Comment by KetanM94** [comment] 2024-05-19 05:21
@Doffy111 
I faced the same issue and found a workaround.
This is how I do it:
Play the video and press back immediately. Then play the same video again. Now you'll see the option to change audio tracks.
I tested with 3 different videos and it worked as I described above.
It may or may not work for you. Please test this and see if it works for you.

**Comment by KetanM94** [comment] 2024-05-19 10:47
Video shown here
https://github.com/Stremio/stremio-bugs/issues/792#issuecomment-2119183655

**Comment by Jefersonpatricio** [comment] 2024-05-25 00:56
@KetanM94 works to me

**Comment by py4747** [comment] 2024-05-28 09:02
@Jefersonpatricio  Only works for some lighter files. try those that are like 80gb and it wont work

**Comment by jaruba** [comment] 2024-06-04 15:39
closing as duplicate of: https://github.com/Stremio/stremio-bugs/issues/792

**Closed by jaruba** 2024-06-04 15:39 UTC
