### ISSUE TITLE
Arabic subtitle selector always set as "active"

### ISSUE THREAD

**Issue by marcusicaro** [Stremio/stremio-bugs#418] opened 2022-10-20 15:48 UTC
**Describe the bug**
When browsing the subtitles avaiable for a movie, the arabic one (اللغة العربية) us always lighted as if is the selected one. Even if you select another language, the arabic one will not change it's color to dark gray.

**To Reproduce**
1. Go to 'any movie with arabic subtitle'
2. Click on 'the language selector for subtitles'
3. Scroll down to 'اللغة العربية'

**Expected behavior**
The arabic subtitle language should always be greyed out instead of whitened.

**Screenshots**
[Bug reproduction](https://imgur.com/WUUYhtx)

**Desktop (please complete the following information):**
 - OS: [I'm using ubuntu but I've seen it also on Windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TRtomasz** [comment] 2022-10-21 07:34
cannot reproduce this issue
![image](https://user-images.githubusercontent.com/40594253/197139465-8bf3cfd1-3736-425b-8040-c397586a64b1.png)
![image](https://user-images.githubusercontent.com/40594253/197139503-52943ad2-554d-4995-9563-21d9970b2d4d.png)
if you can please share additional details about it.

**Comment by marcusicaro** [comment] 2022-10-25 21:11
All right, here are the additional details:
- Any movie where there's arabic subtitle it's like this.
- OS [Ubuntu 22.10]
- UI Language English
- Stremio Ver 4.4.159
- Web UI 4.4.159
- Server 4.19.0

Sorry for taking so long to answer, I'm really busy this week.

If you need additional details I can provide.

**Comment by TRtomasz** [comment] 2022-12-27 12:20
Closing as this can't be reproduced.

**Closed by TRtomasz** 2022-12-27 12:20 UTC
