### ISSUE TITLE
Stremio crashes on amazon firestick 

### ISSUE THREAD

**Issue by Bore1989** [Stremio/stremio-bugs#710] opened 2024-03-13 11:46 UTC
Stremio crashes and restarts when watching larger file size videos - over 4gb...currently using 1.6.7 version but happened on every other version that I've used before. I searched allover the internet and no one has found the solution other then watching smaller size videos or 1080p ones.

**Comment by TRtomasz** [comment] 2024-03-29 12:47
closing as a duplicate of https://github.com/Stremio/stremio-bugs/issues/722

**Closed by TRtomasz** 2024-03-29 12:47 UTC
