### ISSUE TITLE
Suggestion: Add director of movie in Movie Preview

### ISSUE THREAD

**Issue by mattgle** [Stremio/stremio-bugs#539] opened 2023-09-13 18:18 UTC
**Describe the bug**
This is not a bug it's a suggestion. In the TV App you when you are browsing movies, you are able to see the cast of the movie/series but not the director. It would be nice to also have that in the same place.

**To Reproduce**
Go to discover and hover in a movie.

**Expected behavior**
The info of the director should be visible.

**Screenshots**
![WhatsApp Image 2023-09-13 at 3 17 26 PM](https://github.com/Stremio/stremio-bugs/assets/44204622/092fcdc0-cb95-4262-bcd4-ed2c387c5b91)

**Desktop (please complete the following information):**
No info needed

**Smartphone (please complete the following information):**
No info needed

**Additional context**
No additional context needed.

**Comment by TRtomasz** [comment] 2023-10-02 14:13
closing, not a bug.

**Closed by TRtomasz** 2023-10-02 14:13 UTC
