### ISSUE TITLE
Single instance broken on Linux

### ISSUE THREAD

**Issue by michaldaniel** [Stremio/stremio-bugs#45] opened 2016-02-27 23:30 UTC
After opening Stremio, closing it with the "X" button stremio keeps running in the background resulting in being unable to relaunch stremio without first killing the processes. 

OS: elementary OS 0.3.2 freya (Ubuntu 14.04 Based)
Stemio 3.5.7

![zrzut ekranu z 2016-02-28 00 25 30](https://cloud.githubusercontent.com/assets/1345297/13376121/a172e336-ddb2-11e5-9621-7abde2f77fb0.png)

![zrzut ekranu z 2016-02-28 00 25 48](https://cloud.githubusercontent.com/assets/1345297/13376118/6f8530a4-ddb2-11e5-9920-1e3cc05e16ce.png)

**Comment by Ivshti** [comment] 2016-02-27 23:34
@michaldaniel the correct behaviour is:

1. when clicking X, stremio stays opened in the tray
2. when opening stremio again, the running instance gets opened (single-instance)

I think in this case we have two bugs:
1. no tray - but that is an Elementary OS bug
2. single instance doesn't work on Linux

Is it OK if we rename that issue to "Single instance broken on Linux" or we open a new one and close this one?

**Comment by michaldaniel** [comment] 2016-02-27 23:45
@Ivshti It's fine.

> no tray - but that is an Elementary OS bug

I'm wondering if that is true assessment considering that other software display their icons correctly. Is the part responsible for it open source (?), I could take a look. 

>  single instance doesn't work on Linux

Being able to launch it is mine issue here, so sure, if you believe it's better to address it from this way.

**Comment by Ivshti** [comment] 2016-02-27 23:51
@michaldaniel in that case we have an issue with the tray as well 

https://github.com/atom/electron is what we use for runtime and therefore tray

This is the issue: https://github.com/atom/electron/issues/3021
The person who opened the issue explains that it's manifested with Electron 0.33.x, but the maintainer says he can't reproduce it in 0.36.x. Unfortunately, we use 0.33.x and upgrading to next versions is a touchy subject because every electron version brings a load of new issues with it...

**Comment by michaldaniel** [comment] 2016-02-27 23:57
@Ivshti Well then, I can only hope it will happen at some point. Until then my hopes are with you getting the single instance working. Another workaround solution would be to add option not to minimize to try, it's a configurable widely seen in applications.

**Comment by Ivshti** [comment] 2016-02-29 10:28
@michaldaniel maybe "--not-minimize-to-tray" flag? Otherwise minimization to tray was designed so the app can notify you for new episodes/videos

**Comment by michaldaniel** [comment] 2016-03-18 22:24
@Ivshti that sounds great (for now at least), it will make software close and launch as expected. I guess I'm just a person that always uses that setting, minimization to try is something one can agree on but I hate when software doesn't act as ordered to when using "close" button. But that is personal preference, so with that flag it will be even better in my opinion.

**Comment by Ivshti** [comment] 2016-03-22 15:05
@michaldaniel that will be out in the next release (3.5.8)

**Comment by michaldaniel** [comment] 2016-03-25 00:03
@Ivshti I just got an update to 3.5.9, first congratulations on new release, secondly I'm running "./Stremio.sh --not-minimize-to-tray" and it still doesn't close on using "X" button. Is the flag included in that release?

**Comment by Ivshti** [comment] 2016-03-25 06:32
@michaldaniel Try "--disable-minimize-to-tray"

**Comment by michaldaniel** [comment] 2016-03-25 11:37
@Ivshti It works now. Thanks, I'll be telling elementary's community.

**Comment by iachopolo** [comment] 2016-08-15 22:31
Same problem in Arch with Cinnamon desktop. And I had this issue with Linux Mint Cinnamon as well.

**Comment by Ivshti** [comment] 2016-08-16 10:12
@iachopolo is single instance not working for you also?

**Comment by iachopolo** [comment] 2016-08-16 16:48
If I close clicking X I can't reopen it unless I kill the process, yes. That's what you mean, right?

**Comment by iachopolo** [comment] 2016-08-16 16:52
> Another workaround solution would be to add option not to minimize to try, it's a configurable widely seen in applications.
I agree with this. Perhaps that option should come with an explanation, so people would check only if it's not working

**Closed** 2018-12-17 21:31 UTC
