### ISSUE TITLE
Chromecast with Android stops randomly

### ISSUE THREAD

**Issue by thoma202** [Stremio/stremio-bugs#164] opened 2018-09-24 18:33 UTC
Hi,

I'm using stremio on Android with Chromecast.
It works pretty good, but I have an issue, after some random time the app seems to stop and the casting stops as well 

Do you have any ideas where this can come from ? 
Thanks

**Comment by Ivshti** [comment] 2018-09-25 06:29
are you using android 8 or android 9?

If so, we've found issues where android kills stremio after some random period of time. Unfortunately, while the old android versions allowed us to mark stremio as a background service, in the new ones, this is not enough to make it persist for casting.

**Comment by mostlyash** [comment] 2019-04-30 13:31
I've found that with using the new Android you can select apps to not be killed ever. This is to help with battery life, etc. So switching this option should resolve this.

**Comment by hughpearse** [comment] 2021-01-23 22:06
I've had the same issue with Windows-> Chromecast. Not sure of the cause, as I'm also using a steaming plug-in (torrentio). 

Uninstalling (and removing data+configs) and reinstalling resolved the issue. I suspect it was related to the file cache or something like that.

**Comment by TRtomasz** [comment] 2021-07-28 11:08
Fixed with 1.4 release

**Closed by TRtomasz** 2021-07-28 11:08 UTC
