### ISSUE TITLE
Language Error for episode titles

### ISSUE THREAD

**Issue by therealsbeve** [Stremio/stremio-bugs#559] opened 2023-09-29 08:54 UTC
**Describe the bug**
App was working fine but then the language for the episode titles for shows like One Piece and Detective Conan turned to Japanese with seemingly no way around this. The torrents themselves when clicking the episodes are still in English though, but that's pointless when you can't understand what episode you're trying to watch.

**To Reproduce**
1. Go to One Piece or Detective Conan show
2. Click on the show
3. Scroll down to any season and click on it
4. See error: All the episodes are in Japanese.

**Expected behavior**
Episode titles should be in the chose interface language for the app, in my case, English.

**Screenshots**
![Screenshot_20230929_034821_Stremio](https://github.com/Stremio/stremio-bugs/assets/84506246/9e1c034b-d28b-4ccc-adc3-311476bb248f)

**Smartphone (please complete the following information):**
 - Device: S23 Ultra
 - OS: Android 13
 - Version 1.6.6

**Comment by TRtomasz** [comment] 2023-09-29 09:26
this is not a bug, will close it, looks like for some reason the tv db changed names to japanees https://thetvdb.com/series/one-piece/seasons/official/1 we will check if we can on our side bring it back

**Closed by TRtomasz** 2023-09-29 09:26 UTC

**Comment by core1024** [comment] 2023-09-29 12:11
Should be fixed. If not it will got after the cache expires.
