### ISSUE TITLE
Cross device watchlist last played position sync

### ISSUE THREAD

**Issue by menachg** [Stremio/stremio-bugs#469] opened 2023-06-29 10:29 UTC
When playing on android tv stremio app(ccwgtv 4k)
It stays open even if closing the screen
I then you play on another stremio device and go back to the sleeping stremio on android tv the last played position gets overridden by what was last played and still open in android tv

I would expect it ignore current played position if another device updated the position on the same show already.

**Comment by jaruba** [comment] 2023-06-29 10:43
Do you close the video player on Android TV? I think this may be the expected behavior..

The video player will update playback position periodically, in all apps

so if you:
- leave the video player open
- open Stremio on a different device
- go back to Android TV

then it will wake the Android TV device in the video player (at the last known position for the device) which will update the playback position for ur account

If you would instead exit the video player on Android TV when u stop watching, it wouldn't do this

**Comment by menachg** [comment] 2023-06-29 20:20
Yes but when i close the screen i expect the app to quite video instead it just pauses video
Maybe add screen shutoff action setting for example:
*Pause video
*Close video player

**Comment by TRtomasz** [comment] 2024-03-29 11:01
Closing as not a bug

**Closed by TRtomasz** 2024-03-29 11:01 UTC
