### ISSUE TITLE
stremio not working error while applying shell JS.

### ISSUE THREAD

**Issue by ilolaura** [Stremio/stremio-bugs#628] opened 2023-12-19 16:26 UTC
hi, my app stopped working, it was completely fine, and i'm getting the message:

 Error while applying shell JS. Please consider re-installing Stremio from https://www.stremio.com/

i've tried reinstalling many times and it didnt fix the error.

i hope that i can get some help on this issue, thank you.

![Captura de Tela 2023-12-19 às 12 14 20](https://github.com/Stremio/stremio-bugs/assets/154355681/1c62fe7f-8dff-4001-9948-1ddcc85389cc)
![Captura de Tela 2023-12-19 às 12 14 24](https://github.com/Stremio/stremio-bugs/assets/154355681/3899cea3-74e3-458f-9faf-b0e1f24e5ba4)

Desktop version OS: el captain 10.11.6

**Comment by jaruba** [comment] 2023-12-19 16:36
@ilolaura hi, can you try closing the app completely, then removing this folder: "~/Library/Application\ Support/stremio-server/stremio-cache"

then start the app again?

**Comment by jaruba** [comment] 2023-12-19 16:42
@ilolaura sorry, i wrote the wrong folder, this is the folder that should be removed: "~/Library/Application\ Support/Smart\ Code\ ltd"

**Comment by ilolaura** [comment] 2023-12-19 16:51
> @ilolaura sorry, i wrote the wrong folder, this is the folder that should be removed: "~/Library/Application\ Support/Smart\ Code\ ltd"

hi, i couldn't find that folder, only these:
![Captura de Tela 2023-12-19 às 13 49 03](https://github.com/Stremio/stremio-bugs/assets/154355681/35096472-a4be-4fdb-82de-664a062bdd21)

**Comment by jaruba** [comment] 2023-12-19 16:53
@ilolaura the "Contents" folder is not important, the folder i mentioned is there for sure, you can try without the backslash:
`~/Library/Application Support/Smart Code ltd`

**Comment by ilolaura** [comment] 2023-12-19 16:58
> @ilolaura the "Contents" folder is not important, the folder i mentioned is there for sure, you can try without the backslash: `~/Library/Application Support/Smart Code ltd`

ok, i found the folder and removed it to the trash, but after trying to open stremio i'm still getting the same error, it did not fix it. is there anything else i can do??

**Comment by jaruba** [comment] 2023-12-19 17:01
@ilolaura you are using the old v4.4.106 for El Capitan? Downloaded from the website from this link: https://dl.strem.io/mac/v4.4.106/Stremio+4.4.106.dmg ?

**Comment by ilolaura** [comment] 2023-12-19 17:04
> @ilolaura you are using the old v4.4.106 for El Capitan? Downloaded from the website from this link: https://dl.strem.io/mac/v4.4.106/Stremio+4.4.106.dmg ?

yes right, i've downloaded this version Stremio+4.4.106 from their website. i also tried unistalling and reinstalling many times, nothing works.

**Comment by jaruba** [comment] 2023-12-19 17:13
@ilolaura that only thing you can try to do for now, is to run the app with the following command line argument: `--webui-url=https://app.strem.io/#/`

while we look into the issue further, the problem is that El Capitan to Sierra users use a very old version of the app (v4.4.106) and can never update to the latest versions (currently v4.4.165) because the OS is very old (El Capitan was released more than 8 years ago, specifically September 2015)

**Comment by ilolaura** [comment] 2023-12-19 17:32
> @ilolaura that only thing you can try to do for now, is to delete the cache folder that i mentioned again, and run the app with the following command line argument: `--webui-url=https://app.strem.io/#/`
> 
> while we look into the issue further, the problem is that El Capitan to Sierra users use a very old version of the app (v4.4.106) and can never update to the latest versions (currently v4.4.165) because the OS is very old (El Capitan was released more than 8 years ago, specifically September 2015)

are these folders the right ones? i've trashed both 
![Captura de Tela 2023-12-19 às 14 28 36](https://github.com/Stremio/stremio-bugs/assets/154355681/18013619-6354-473d-a922-717eb06fb621)
when trying to use the command it does not work:
![Captura de Tela 2023-12-19 às 14 29 20](https://github.com/Stremio/stremio-bugs/assets/154355681/152ec605-8e98-4684-b1b2-c336654c8462)

**Comment by jaruba** [comment] 2023-12-19 17:39
@ilolaura not like that, the full command is:
```
./Applications/Stremio.app/Contents/MacOS/stremio --webui-url=https://app.strem.io/#/
```

**Comment by ilolaura** [comment] 2023-12-19 17:43
> @ilolaura not like that, the full command is:
> 
> ```
> ./Applications/Stremio.app/Contents/MacOS/stremio --webui-url=https://app.strem.io/#/
> ```

![Captura de Tela 2023-12-19 às 14 40 38](https://github.com/Stremio/stremio-bugs/assets/154355681/8e201d3a-7991-4c13-8062-0cda33029bb7)
still not working

**Comment by jaruba** [comment] 2023-12-19 17:49
@ilolaura 
should work if you split it into 2 commands:
```
cd /Applications/Stremio.app/Contents/MacOS
./stremio --webui-url=https://app.strem.io/#/
```

**Comment by ilolaura** [comment] 2023-12-19 18:04
> @ilolaura should work if you split it into 2 commands:
> 
> ```
> cd /Applications/Stremio.app/Contents/MacOS
> ./stremio --webui-url=https://app.strem.io/#/
> ```

yay it finally worked! 
btw i tested opening it without using the terminal but it does not work, i keep getting the same error, meaning if i wanna use stremio i always have use the command, right?

thank you so much for your help! :)

**Comment by jaruba** [comment] 2023-12-19 18:22
@ilolaura for the moment, i believe that you would need to use those commands to run it, we will still try to look into the issue to see if we can find a solution (so this may be fixed within the next few days, with a bit of luck), but the truth is that sooner or later support for very old versions of MacOS will inevitably need to be removed.. as such issues will continue to appear in time until we won't be able to spare the effort to keep them available.. hopefully that day won't be today and we will find the solution we need to prolong support for El Capitan and Sierra OS versions

**Comment by ilolaura** [comment] 2023-12-19 19:09
Got it, thanks for informing me. Hopefully, the older versions will continue to function without any issues!

**Comment by Targusk** [comment] 2023-12-19 22:29
I have the same issue but with my macbook pro. I don't find the cache folder...

**Comment by jaruba** [comment] 2023-12-19 22:57
@Targusk just try using these commands in a terminal: https://github.com/Stremio/stremio-bugs/issues/628#issuecomment-1863228751

**Comment by Targusk** [comment] 2023-12-19 23:26
It doesn't work, they say: "qt.network.ssl: Error receiving trust for a CA certificate"

**Comment by jaruba** [comment] 2023-12-19 23:36
@Targusk that is a completely different issue and it is a problem with ur device, not with Stremio, it can happen even if ur time / date is wrong on ur device, but my guess is that for you it happens because u have missed too many MacOS updates, which caused your device to have a very old lists of available trusted root certificates, i would be surprised if u don't get similar ssl issues accessing sites in the browser too

as this is not a Stremio issue, I cannot assist in finding a solution.. if i were you, i would probably try googling something like "update list of trusted root certificates macos"

**Comment by jaruba** [comment] 2023-12-20 11:07
@ilolaura we think we may have found the issue, can you try opening the app to see if it works for you?

**Comment by ilolaura** [comment] 2023-12-20 20:07
> @ilolaura we think we may have found the issue, can you try opening the app to see if it works for you?

still not working

![Captura de Tela 2023-12-20 às 17 04 10](https://github.com/Stremio/stremio-bugs/assets/154355681/beef574c-0980-4356-a7aa-8fd66aada0d8)
![Captura de Tela 2023-12-20 às 17 04 21](https://github.com/Stremio/stremio-bugs/assets/154355681/5b4d1599-5155-483e-b008-6fecd625eda1)
![Captura de Tela 2023-12-20 às 17 04 26](https://github.com/Stremio/stremio-bugs/assets/154355681/37e75497-2827-45da-97e9-df480699433b)

**Comment by jaruba** [comment] 2023-12-21 21:28
@ilolaura it should be working now

**Closed by jaruba** 2023-12-21 21:28 UTC
