### ISSUE TITLE
Subtitle menu crashes sometimes when you are scrolling (Desktop)

### ISSUE THREAD

**Issue by rasoulbsd** [Stremio/stremio-bugs#581] opened 2023-10-18 20:18 UTC
**Describe the bug**
When you are scrolling to reach downer subtitles, it sometimes automaticlly disappeared. It is not the case but it is like its modal has some spaces which when the mouse pointer goes over, the modal become closed.
- I've tested some times in order to reproduce the problem.
- Iّt is occuring in both fullscreen and normal play.
- It is happening both in paused and playing mode.
- All my friends who uses this app also has this problem sometimes.
- This problem resides from last updates and it is not new, I am just reporting now.

**To Reproduce**
At first I tried on my already opened stremio but I couldn't reproduce it. I just force closed the app and turned my VPN and opened the app and went to the same video I was watching and now, it has the problem (the attached video is from this test).
1. Go to a random movie
2. Mouse over the sutitle button
3. Scroll down and up some times with different speeds.
4. See the problem

**Expected behavior**
Flawless experience :))

**Screenshots**

https://github.com/Stremio/stremio-bugs/assets/35425167/04ccc65f-4b23-4d90-8c33-61664e729706

**Desktop
 - OS: MacOS Ventura (Version 13.4.1)
<img width="129" alt="Screenshot 2023-10-18 at 11 37 29 PM" src="https://github.com/Stremio/stremio-bugs/assets/35425167/229cb33c-0ba8-4483-9dbe-943a2fe4d553">

**Additional context**
My guess (with zero knowledge on ur app) is like it is reloading to fetch subtitles and it crashes sometime (I mentioned the VPN in above text because of this) but I couldn't test it.

**Comment by zargarzadehm** [comment] 2023-10-18 20:40
> **Describe the bug** When you are scrolling to reach downer subtitles, it sometimes automaticlly disappeared. It is not the case but it is like its modal has some spaces which when the mouse pointer goes over there, the modal become closed.
> 
> * I've tested some times in order to reproduce the problem.
> * I've have tested it is occuring in both fullscreen and normal play.
> * It is happening both in paused and playing mode.
> * All my friends who uses this app also has this problem sometimes.
> * This problem resides from last updates and it is not new, I am just reporting now.
> 
> **To Reproduce** At first I tried on my already opened stremio but I couldn't reproduce it. I just force closed the app and turned my VPN and opened the app and went to the same video I was watching and now, it has the problem.
> 
> 1. Go to a random movie
> 2. Mouse over the sutitle button
> 3. Scroll down and up some times with different speeds.
> 4. See the problem
> 
> **Expected behavior** Flawless experience :))
> 
> **Screenshots**
> 
>  Screen.Recording.2023-10-18.at.11.29.30.PM.mp4 
> 
> **Desktop
> 
> * OS: MacOS Ventura (Version 13.4.1)
> 
> <img alt="Screenshot 2023-10-18 at 11 37 29 PM" width="129" src="https://user-images.githubusercontent.com/35425167/276386633-229cb33c-0ba8-4483-9dbe-943a2fe4d553.png">
> **Additional context** My guess (with zero knowledge on ur app) is like it is reloading to fetch subtitles and it crashes sometime (I mentioned the VPN in above text because of this) but I couldn't test it.

I've had the same problem for a long time, both with old versions and new versions!

**Comment by TRtomasz** [comment] 2023-10-19 11:26
closing as duplicate of https://github.com/Stremio/stremio-bugs/issues/284

**Closed by TRtomasz** 2023-10-19 11:26 UTC
