### ISSUE TITLE
Incorrect Calendar dates to day mapping

### ISSUE THREAD

**Issue by OjasMansata** [Stremio/stremio-bugs#492] opened 2023-08-26 05:12 UTC
**Describe the bug**
The first Calendar day starts on Monday every month by default. The date-to-day mapping is incorrect.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by P-Jay357** [comment] 2023-08-26 16:45
This is a duplicate of the bug I raised last night - https://github.com/Stremio/stremio-bugs/issues/487

**Closed** 2023-08-29 09:23 UTC
