### ISSUE TITLE
Stremio playback continues at the end of video file

### ISSUE THREAD

**Issue by traincodesleep** [Stremio/stremio-bugs#745] opened 2024-04-11 03:09 UTC
**Describe the bug**
At the end of some .mkv files, Stremio does not end playback and go to the next episode or back to the current episode screen. The screen remains black, the seek bar is at the end, but the timer/counter keeps going, incrementing and surpassing the length of the video.

**To Reproduce**
Play a file then watch or seek to the end.

**Expected behavior**
At the end of playback, Stremio should go to the next episode or return to the episode screen. However the playback counter just continues to increment, and nothing else happens.

**Screenshots**
![WhatsApp Image 2024-04-10 at 22 53 09_3bb1713c](https://github.com/Stremio/stremio-bugs/assets/31750524/f2501c3f-ed00-4d90-a8a2-7a742ea0e8ef)
![WhatsApp Image 2024-04-10 at 22 53 09_7640a505](https://github.com/Stremio/stremio-bugs/assets/31750524/f90b3c60-f2d7-4da1-a599-7ea752394f67)

**TV :**
 - Device: Fire TV Stick 4K Max
 - OS: FireOS 
 - Version: FireOS 7.2.5.5
 - Stremio Version: 1.6.9

**Additional context**
This does not seem to happen with every file or show. I have also noticed that the "green" skip credits button disappears once the end of the file is reached (so stremio is aware that the video is done playing), however the "playback" still continues with the counter near the seek bar continuing to increment.

**Comment by traincodesleep** [comment] 2024-04-11 14:32
Hi. The exact issue appears to happen with stream American.Horror.Story.S11E01.Somethings.Coming.2160p.HULU.WEB-DL.DDP5.1.H.265-NTb.mkv (4.79GB) which is part of series pack American.Horror.Story.S11.2160p.HULU.WEB-DL.x265.10bit.SDR.DDP5.1-NTb[rartv].

From my testing this doesn't happen with other files in the series pack. Just the first one.

**Comment by TRtomasz** [comment] 2024-04-11 16:27
cant reproduce everything is fine on my chromecast

**Comment by traincodesleep** [comment] 2024-04-11 22:18
I've done some additional testing on my other devices with the same stream. The issue appears to only be present on the Fire TV Stick 4K Max when the "Tunneled Playback" option is enabled in playback settings. Since there is already a warning that there might be "Possible playback issues on some devices", I guess we can close this as a device specific issue. The issue was resolved by turning Tunneled Playback off.

**Comment by TRtomasz** [comment] 2024-04-12 07:28
Will close it then, issue is clearly with the exoplayer and there is nothing we can do about this, only wait for the updated exo. Thank you for your support.

**Closed by TRtomasz** 2024-04-12 07:28 UTC
