### ISSUE TITLE
trakt.tv not marking watched

### ISSUE THREAD

**Issue by BatFC** [Stremio/stremio-bugs#7] opened 2015-11-05 01:38 UTC
Every tv show that I have watched is not getting marked as watched in trakt.tv. Trakt is successfully connected to stremio and can tell when I am watching a tv show. But trakt will not mark it watched after I finish the show.

**Comment by Ivshti** [comment] 2015-11-05 12:59
I'd like to add that sync doesn't work too.

**Comment by evansantos** [comment] 2016-04-05 14:20
I thought that I was alone on this... ![stacerizz-sad-ben-affleck-depressed-l0NhWEW8ZkstMCGK4](https://camo.githubusercontent.com/4e60de2d419c3db48bb21d266acd88d7821eb70b/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f6c304e68574557385a6b73744d43474b342f67697068792e676966)

**Comment by Ivshti** [comment] 2016-04-12 07:17
I'm putting it on the roadmap

**Comment by Ivshti** [comment] 2016-04-13 19:35
@BatFC @evansantos I have the problem of reproducing this

does it scrobble?

does trakt show that the episode/movie is playing?

**Comment by evansantos** [comment] 2016-04-13 19:40
@Ivshti It shows on trakt.tv that episode/movie is playing but when its end doesn't scrobble 

![cat-sad-M9yC8b0x7Y7oA](https://camo.githubusercontent.com/59283e930476dcd45e9e96fe9dcda3c412016355/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f4d397943386230783759376f412f67697068792e676966)

**Comment by evansantos** [comment] 2016-04-13 19:41
Another thing is there's a way to log out from trakt.tv? maybe revoking after loggin out could correct it, what you think @Ivshti ?

**Comment by Ivshti** [comment] 2016-04-13 19:48
@evansantos got it, that helps; are you letting the episode finish until the end or stopping it right before?

re other issue: it has to detect if authentication token fails i guess..currently it just checks if it's theoretically expired (past it's date)

**Comment by Ivshti** [comment] 2016-04-13 19:57
@evansantos I did something stupid.
 scrobbling stop event is only fired if you exit the player... which means that if the next ep begins automatically the previous won't be scrobbled

Any chance this is consistent with your issue?

**Comment by evansantos** [comment] 2016-04-15 14:30
@Ivshti I've revoke strem.io token and stills there... not working at all :cry: 
I think it is possible, because I never close my strem.io :laughing:

**Comment by Ivshti** [comment] 2016-04-15 14:36
@evansantos yep - that's how it works at the moment, no way to revoke it 

I'll get down to implementing that at some point - probably along with sync functionality

**Comment by Ivshti** [comment] 2016-04-15 14:36
Or maybe now so it's on the next version..

**Comment by Ivshti** [comment] 2016-04-15 15:05
Ok, done
Will be on the next version

**Comment by evansantos** [comment] 2016-05-03 01:01
@Ivshti thank you! It's now working like a charm :D

maybe you now can close this issue

**Closed** 2016-05-03 10:37 UTC
