### ISSUE TITLE
update appimage not works

### ISSUE THREAD

**Issue by Alexis6307** [Stremio/stremio-bugs#162] opened 2018-09-13 15:21 UTC
Title explain itself. The appimage update functionallity doesn't works.

**Comment by Ivshti** [comment] 2018-09-16 19:05
i will close this as a duplicate of: https://github.com/Stremio/stremio-bugs/issues/163

even though your issue is older, the other has a stack trace

ther eare other duplicates as well

we're working on a fix of this, but for now it's possible to compile http://github.com/stremio/stremio-shell yourself

**Closed by Ivshti** 2018-09-16 19:05 UTC
