### ISSUE TITLE
Chromecast subtitles align not working

### ISSUE THREAD

**Issue by roydbt** [Stremio/stremio-bugs#81] opened 2016-10-29 14:37 UTC
When I press G/H it says in the computer the message but not effect on TV even if I change to different subtitles and returning which makes the stream restart.

**Comment by Ivshti** [comment] 2016-11-02 00:31
This is the same as many other issues opened here

Will be resolved in the next major release scheduled for December

At the moment the refactor that we'd need to do on the current branch isn't justified considering in the next release (4.0) it's fixed by design and we're putting finishing touches there

Also, tip: you can change the subtitles variant with the "wrong subtitles" box, which can often resolve sync issues

**Closed** 2018-07-12 13:40 UTC
