### ISSUE TITLE
Can't start on Linux.

### ISSUE THREAD

**Issue by SvetoslavAsenov** [Stremio/stremio-bugs#261] opened 2021-01-31 11:12 UTC
**Describe the bug**
`"error while loading shared libraries: libx264.so.152: cannot open shared object file: No such file or directory"`

**Desktop (please complete the following information):**
 - OS: MX Linux
 - Version 4.4

**Comment by TRtomasz** [comment] 2021-02-01 13:10
duplicate of https://github.com/Stremio/stremio-shell/issues/106

**Closed by TRtomasz** 2021-02-01 13:10 UTC
