### ISSUE TITLE
Linux Mint 20 (Ubuntu 20.04 based): error while loading shared libraries: libx264.so.152

### ISSUE THREAD

**Issue by henriquedesousa** [Stremio/stremio-bugs#255] opened 2021-01-04 10:35 UTC
**Describe the bug**
While trying to run stremio after installing the latest .deb file, I'm getting:

`stremio: error while loading shared libraries: libx264.so.152: cannot open shared object file: No such file or directory`

**To Reproduce**
**Desktop (please complete the following information):**
 - OS: Linux Mint 20 (based on Ubuntu 20.04)

**Additional context**
I have another box with Linux Mint 19.3 which is based on Ubuntu 18.04 and it's working just fine.

**Comment by Ivshti** [comment] 2021-01-04 12:06
Closing as a duplicate of https://github.com/Stremio/stremio-shell/issues/106

**Closed by Ivshti** 2021-01-04 12:06 UTC
