### ISSUE TITLE
Subtitle size of Mac not saving

### ISSUE THREAD

**Issue by KavGoat** [Stremio/stremio-bugs#561] opened 2023-10-02 10:05 UTC
**Describe the bug**
Setting the subtitle size on Mac to 72%. For https streams with embedded subs, the size is not 72%, instead it is 180% size but bottom right says 72%. To fix, have to press + then -, to resize back to 72%.

**To Reproduce**
1. Set size to 72% in settings
2. Play stream with embedded subs

**Expected behavior**
It should remembers the 72% form settings. It is definite not the expected belabour as pressing plus and minus can actually fix th problem, so it is a bug.

**Screenshots**
<img width="461" alt="image" src="https://github.com/Stremio/stremio-bugs/assets/86602648/03f8b5f3-3e3c-4929-9fc1-d9720509ccbb">

![IMG_0212](https://github.com/Stremio/stremio-bugs/assets/86602648/c5d27792-c414-484a-951f-4395e6995670)

<img width="571" alt="image" src="https://github.com/Stremio/stremio-bugs/assets/86602648/07e2ac9c-28e0-45d0-ab48-4ef3d81a406c">

**Desktop (please complete the following information):**
macOS Sonoma, m2 Mac

**Comment by TRtomasz** [comment] 2023-10-02 11:37
closing as a duplicate of https://github.com/Stremio/stremio-bugs/issues/422

**Closed by TRtomasz** 2023-10-02 11:37 UTC
