### ISSUE TITLE
Subtitulos não funcionam em Google Tv. Xiaomi Mi box 2 generation

### ISSUE THREAD

**Issue by Seno1963** [Stremio/stremio-bugs#585] opened 2023-10-22 01:01 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gp2mv3** [comment] 2023-10-22 10:12
Duplicate of #583

**Comment by jaruba** [comment] 2023-10-22 17:02
as stated, it is a duplicate, check the other issue pls

**Closed by jaruba** 2023-10-22 17:02 UTC
