### ISSUE TITLE
Subtitles disabling by itself on one show but still enabled on others

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#331] opened 2021-11-25 14:15 UTC
**Describe the bug**
In one specific tv show [Boruto: Naruto Next Generations] (embedded) subtitles turns off themselves every time I go back from the playing or load next episode. Nevertheless at the same time when I open any other show the subtitles are enabled.

**To Reproduce**
1. Open an episode of the pointed tv show
2. Enable the subtitles
3. Go back from playing and play again the episode or just load the next episode
4. Subtitles are off
5. Open any another tv show (that doesn't need subtitles) and see that subtitles are on

**Expected behavior**
Subtitles should still be turned on for the show it was enabled in the first place.
But secondly if the subtitles turned themselves off there then they shouldn't be still on in another show.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
![image](https://user-images.githubusercontent.com/17256400/143456708-b2b1a95c-551b-438c-9a4e-159e2b65000e.png)

**Comment by TRtomasz** [comment] 2022-03-03 15:50
I'm not able to reproduce your issue at all, tried with naruto next generation and everything works just fine, tried first 10 episodes and there was no problem at all

**Comment by maxoku** [comment] 2022-03-03 17:37
@TRtomasz Yes, as I checked it out now, the subs aren't turning themselves anymore in that show, so I guess it was fixed along the way. Unfortunately, there are other problems. I've watched another show today and the subs appeared while being disabled, so I had to enable them and disable again. Seems that enabling the subs in one show can have strange effects on other ones.

**Comment by TRtomasz** [comment] 2023-09-28 09:07
Closing as not reproduciable. There is known issue that if there are only embedded subs they will not be selected automatically.

**Closed by TRtomasz** 2023-09-28 09:07 UTC
