### ISSUE TITLE
Subtitles will not turn off

### ISSUE THREAD

**Issue by PrivateGiles** [Stremio/stremio-bugs#202] opened 2019-12-01 00:52 UTC
I'm unable to switch off subtitles within the app. 
I've uninstalled the opensubtitles add-on but still subtitles are there.

**Comment by Greggaz** [comment] 2019-12-04 22:07
Any updates from the development team? -

**Comment by TRtomasz** [comment] 2019-12-04 22:37
Hi, you didn't provide any details about your device,system and stremio setaup(what version) so it is not possible to help you. Please update your ticket with needed information.

**Comment by Greggaz** [comment] 2019-12-04 22:41
Hi, 

I'm currently running a Nvidia Shield
Currently running version 8.0
(32.5.205.75)
Model number: P2897
Version: 9
Patch levels: 5th July 2019

**Comment by Greggaz** [comment] 2019-12-04 22:42
The version of the app I'm running is also version 1.2.16

**Comment by TRtomasz** [comment] 2019-12-04 23:01
Please tell us what video did you try  to watch? Maybe it has embedded subtitles so it is not possible to not display them

**Comment by Greggaz** [comment] 2019-12-04 23:48
Hi,

This happens on any program that I watch this is not on any particular tv / movie that I select on stremio. I used to be able to switch the subtitles off using my remote and switching them off in settings but due to another open issue to do with navigation I can't do this.

**Comment by Greggaz** [comment] 2019-12-04 23:51
The only way I've found to remove the subtitles is by making stremio open using the android media player which when I play the film / TV show it does not display subtitles

**Comment by TRtomasz** [comment] 2019-12-05 08:45
As a workaround i recommend go to the settings and set default subtitles language to some exotic language so it will be almost not possible for addon to find subtitles in that way you will not have subtitles displayed.

**Comment by Greggaz** [comment] 2019-12-05 20:49
Thanks for the workaround - I'll give this a try tonight. 
Do you know when this will be fixed in the main release? 
Thanks

**Comment by Greggaz** [comment] 2019-12-05 23:36
Hi I can confirm that choosing the symbols as the default subtitles fixes this issue. 

![15755889735584804894980295953369](https://user-images.githubusercontent.com/56416493/70283131-10b5e980-17b8-11ea-8f3f-4f456525f937.jpg)

**Comment by Greggaz** [comment] 2019-12-24 00:55
Do you know when this issue will be fixed in the app without having to make this change

**Comment by juliofc** [comment] 2020-07-23 21:29
I have the same issue, in running stremio 1.2.22 using Android 10 on Galaxy Tab S6 Lite and Chromecast 3. I'm also unable to turn subtitles off for many movies

**Comment by TRtomasz** [comment] 2020-08-17 07:39
Hi, now option to turn off subtitles is available in Android version.

**Closed by TRtomasz** 2020-08-17 07:39 UTC
